apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: contatore
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: contatore
  updatePolicy:
    updateMode: "Off"
  resourcePolicy:
    containerPolicies:
      - containerName: web
        minAllowed:
          cpu: 50m
          memory: 32Mi
        maxAllowed:
          cpu: "1"
          memory: 512Mi
