apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-locale
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manuale
  hostPath:
    path: /tmp/pv-locale
