apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: contatore-produzione
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/rscaramu/contatore-deploy
    targetRevision: main
    path: overlays/produzione
  destination:
    server: https://kubernetes.default.svc
    namespace: produzione
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
