apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sviluppatore
rules:
  - apiGroups: ["", "apps", "batch"]
    resources:
      - pods
      - pods/log
      - services
      - configmaps
      - deployments
      - replicasets
      - jobs
      - cronjobs
    verbs: ["get", "list", "watch", "create", "update",
            "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods/exec", "pods/portforward"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: squadra-web-sviluppo
  namespace: sviluppo
subjects:
  - kind: Group
    name: squadra-web
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: sviluppatore
  apiGroup: rbac.authorization.k8s.io
