apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-redis
spec:
  schedule: "0 3 * * *"
  timeZone: "Europe/Rome"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: backup
              image: redis:7-alpine
              command: ["sh", "-c",
                "redis-cli -h redis-0.redis BGSAVE"]
