apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: produzione
resources:
  - ../../base
  - pdb.yaml
replicas:
  - name: contatore
    count: 4
images:
  - name: ghcr.io/rscaramu/contatore
    newTag: "2.1"
patches:
  - path: risorse.yaml
  - target:
      kind: Deployment
      name: contatore
    patch: |
      - op: add
        path: /spec/template/spec/containers/0/envFrom
        value:
          - configMapRef:
              name: contatore-config
