apiVersion: apps/v1
kind: Deployment
metadata:
  name: contatore
spec:
  replicas: 3
  selector:
    matchLabels:
      app: contatore
  template:
    metadata:
      labels:
        app: contatore
    spec:
      containers:
        - name: web
          image: ghcr.io/rscaramu/contatore:2.0
          ports:
            - name: http
              containerPort: 8000
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              memory: 128Mi
          startupProbe:
            httpGet:
              path: /
              port: http
            failureThreshold: 30
            periodSeconds: 2
          readinessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 10
            failureThreshold: 3
