apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "contatore.fullname" . }}-migrazione
  annotations:
    helm.sh/hook: pre-upgrade,pre-install
    helm.sh/hook-weight: "0"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrazione
          image: redis:7-alpine
          command: ["sh", "-c",
            "echo migrazione schema; sleep 2"]
