apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: contatore-rs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: contatore
  template:
    metadata:
      labels:
        app: contatore
    spec:
      containers:
        - name: web
          image: ghcr.io/rscaramu/contatore:2.0
